on:
  pull_request:
    types:
    - opened
    - synchronize
    - closed
  push:
    paths-ignore:
    - '**/*.md'
    branches:
    - main

jobs:
  main_commit_build:
    name: Build main branch commit
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          gravel
        key: ${{ github.event.base_ref }}-${{ github.event.after }}
        restore-keys: |
          ${{ github.event.base_ref }}-${{ github.event.before }}
    - uses: actions/setup-go@v3
      with:
        cache: true
    - run: go install github.com/emm035/gravel/cmd/gravel@latest
    - run: gravel build


  pr_build:
    name: Build PR
    runs-on: ubuntu-22.04
    if: github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          gravel
        key: ${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.ref }}
        restore-keys: |
          ${{ github.event.pull_request.head.ref }}
          ${{ github.event.pull_request.base.ref }}-${{ github.event.pull_request.base.sha }}
    
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        path: head
    - uses: actions/setup-go@v3
      with:
          cache: true
    - run: go install github.com/emm035/gravel/cmd/gravel@latest
    - run: gravel build
