on:
  pull_request:
    types:
    - opened
    - synchronize
    - closed
  push:
    paths-ignore:
    - '**/*.md'
    - '/example/**/*'
    branches:
    - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    # Only used for pull requests
    - uses: actions/cache@v3
      if: github.event_name == 'pull_request'
      with:
        path: gravel/cache.json
        key: ${{ github.event.pull_request.head.ref }}-${{ github.event.pull_request.head.ref }}
        restore-keys: |
          ${{ github.event.pull_request.head.ref }}
          ${{ github.event.pull_request.base.ref }}-${{ github.event.pull_request.base.sha }}

    # Only used for pushes to main
    - uses: actions/cache@v3
      if: github.event_name == 'push'
      with:
        path: gravel/cache.json
        key: ${{ github.ref_name }}-${{ github.event.after }}
        restore-keys: ${{ github.ref_name }}-${{ github.event.before }}

    - uses: hashicorp/setup-golang@v1
      with: { version-file: go.mod }

    - run: go install github.com/emm035/gravel/cmd/gravel@latest

    - run: gravel build --version.strategy=date

    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USR }}
        password: ${{ secrets.DOCKER_HUB_PAT }}

    - uses: docker/build-push-action@v3
      with:
        push: true
        tags: emm035/procfly:latest

    - uses: stefanzweifel/git-auto-commit-action@v4.16.0
      if: github.event_name == 'push' || github.event.pull_request.merged
      with:
        commit_message: Update version files
